version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: campanhas360
      POSTGRES_USER: bolt360ti
      POSTGRES_PASSWORD: "kasdjasidaau1n213mmaaasdncksk"
    ports:
      - '4001:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - saas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bolt360ti -d campanhas360"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "Bolt36023@"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - saas-network

volumes:
  postgres-data:
  minio-data:

networks:
  saas-network:
    name: saas-network
    driver: bridge
